:myfor
nslookup www.baidu.com
nslookup www.youku.com
nslookup www.iqiyi.com
nslookup www.163.com
nslookup www.126.com
nslookup www.qq.com
nslookup www.csdn.net
nslookup www.5566.net
nslookup www.ip138.com
nslookup email.163.com
nslookup blog.sina.com.cn
nslookup www.cctv.com
nslookup www.youtube.com
nslookup www.facebook.com
nslookup www.888msc.com
nslookup www.google.com
nslookup www.888msc.com
nslookup www.19suncity.com
nslookup www.xmrc.com
nslookup joke.a9898.com
nslookup m.weather.com.cn
nslookup mov.a9898.com
nslookup a.alimama.cn
nslookup hao123.com
nslookup www.126.com
nslookup www.qq.com
nslookup www.csdn.net
nslookup www.bind9.net
nslookup niutuku.com
nslookup www.bind.com
nslookup twitter.com
nslookup ohgf.org
nslookup asikjk2j3khlh23h2khj.com
nslookup asikjk2adsfahlh23h2khj.com
nslookup asikjk2asadsfahlh23h2khj.com
nslookup aa23adsfahlh23h2khj.com
nslookup bbs.chinaunix.net
nslookup blog.51cto.com
nslookup f.dataguru.cn
nslookup lfs.tmuniz.com
goto myfor
pause